### ISSUE TITLE
macos (big sur) icons just question box

### ISSUE THREAD

**Issue by heresy0-0y** [peinan/iterm2-statusbar-components#7]
hi, i have both the status bar font and iterm2 profile font set to a nerd font (i've tried many for both) but no matter what the glyphs show only as question mark boxes
<img width="295" alt="Screen Shot 2021-03-03 at 12 55 26 PM" src="https://user-images.githubusercontent.com/67918668/109856964-bb1cf680-7c1f-11eb-9b99-4bd6b4a30286.png">

**Comment by peinan** [comment]
I'm sorry for the late response that I didn't notice this issue.
This may be caused by the mismatch of the character code of SFMono Square font with the font you set. Is this problem still happen when SFMono Square font is set?
Or you can set your custom icons by editing [character codes in the script](https://github.com/peinan/iterm2-statusbar-components/blob/master/components/weatherinfo.py#L24-L32) if you want to use other fonts.

Please feel free to ask anything.

**Comment by peinan** [comment]
Closing this issue because there has been no response.
